import './globals.css';

import { languages } from 'common/libs/i18n/settings';
import Navigation from 'components/Navigation/Navigation';
import SessionProvider from 'contexts/SessionProvider';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const RootLayout = ({ children, lng }: { children: React.ReactNode; lng: any }) => {
  return (
    <SessionProvider>
      <html lang={lng}>
        <body className={inter.className}>
          <div className="flex min-h-screen flex-col">
            <Navigation />
            {children}
          </div>
        </body>
      </html>
    </SessionProvider>
  );
};

export default RootLayout;
